// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf2dFSKEy111Wmp2Dl3tgujK4SFnhbbSs',
    appId: '1:898469566049:web:0eb7a77f1f81a123ff7c20',
    messagingSenderId: '898469566049',
    projectId: 'kindcart-a409d',
    authDomain: 'kindcart-a409d.firebaseapp.com',
    storageBucket: 'kindcart-a409d.firebasestorage.app',
    measurementId: 'G-FK1XKM0PWP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI7Ik6YUtEbYVL1rOs-2cofsW8lsZD3Kc',
    appId: '1:898469566049:ios:2368dbcf61d0b4fbff7c20',
    messagingSenderId: '898469566049',
    projectId: 'kindcart-a409d',
    storageBucket: 'kindcart-a409d.firebasestorage.app',
    iosBundleId: 'com.example.kindcart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI7Ik6YUtEbYVL1rOs-2cofsW8lsZD3Kc',
    appId: '1:898469566049:ios:2368dbcf61d0b4fbff7c20',
    messagingSenderId: '898469566049',
    projectId: 'kindcart-a409d',
    storageBucket: 'kindcart-a409d.firebasestorage.app',
    iosBundleId: 'com.example.kindcart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf2dFSKEy111Wmp2Dl3tgujK4SFnhbbSs',
    appId: '1:898469566049:web:eae420cfe2a80136ff7c20',
    messagingSenderId: '898469566049',
    projectId: 'kindcart-a409d',
    authDomain: 'kindcart-a409d.firebaseapp.com',
    storageBucket: 'kindcart-a409d.firebasestorage.app',
    measurementId: 'G-39TDL295C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt-nIHVELa9U2XyJXsW_5rXN-hvONR3aE',
    appId: '1:898469566049:android:116b2c9662096d93ff7c20',
    messagingSenderId: '898469566049',
    projectId: 'kindcart-a409d',
    storageBucket: 'kindcart-a409d.firebasestorage.app',
  );

}